feature/leave-spaces-in-docblock
eonx-com/easy-quality pull request #12
Opened 2021-09-23 15:59 UTC by alexndlm

-leave spaces in doc comments
-update packages
-refactoring

2021-10-01 06:37 UTC, itorgov requested changes

2021-10-01 06:37 UTC, itorgov commented on src/Rector/AddSeeAnnotationRector.php
>          /** @var \Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo|null $phpDocInfo */
Please remove `null`.

2021-10-01 06:37 UTC, itorgov commented on src/Rector/PhpDocBlockTrait.php
> +            $phpDocInfo->getPhpDocNode()->children = array_merge($newComments, $phpDocInfo->getPhpDocNode()->children);
`\array_merge`

2021-10-01 06:37 UTC, itorgov commented on src/Rector/PhpDocCommentRector.php
> +        if ($phpDocTextNode->getAttribute('orig_node')
`$phpDocTextNode->getAttribute('orig_node') !== null`

2021-10-01 06:37 UTC, itorgov commented on tests/Rector/PhpDocReturnForIterableRector/Fixture/parent_method_has_docblock.php.inc
> +    abstract public static function provideData1(): iterable;
Why do you use `1` at the end?

2021-10-01 06:37 UTC, itorgov commented on tests/Rector/ReturnArrayToYieldRector/Fixture/should_not_remove_doc_blocks.php.inc
> +         * @doto Let's pretend that this comment is extremely important and meaningful.
Maybe `@todo`?

2021-10-01 09:24 UTC, alexndlm commented on src/Rector/AddSeeAnnotationRector.php
>          /** @var \Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo|null $phpDocInfo */
Done.

2021-10-01 09:24 UTC, alexndlm commented on src/Rector/PhpDocBlockTrait.php
> +            $phpDocInfo->getPhpDocNode()->children = array_merge($newComments, $phpDocInfo->getPhpDocNode()->children);
Done.

2021-10-01 09:24 UTC, alexndlm commented on src/Rector/PhpDocCommentRector.php
> +        if ($phpDocTextNode->getAttribute('orig_node')
Done.

2021-10-01 09:24 UTC, alexndlm commented on tests/Rector/PhpDocReturnForIterableRector/Fixture/parent_method_has_docblock.php.inc
> +    abstract public static function provideData1(): iterable;
Done.

2021-10-01 09:25 UTC, alexndlm commented on tests/Rector/ReturnArrayToYieldRector/Fixture/should_not_remove_doc_blocks.php.inc
> +         * @doto Let's pretend that this comment is extremely important and meaningful.
Done.

2021-10-04 08:35 UTC, roman-eonx requested changes

2021-10-04 08:35 UTC, roman-eonx commented on src/Rector/PhpDocReturnForIterableRector.php
> +            // possibly trait
```suggestion
            // Possibly a trait
```

2021-10-04 08:35 UTC, roman-eonx commented on src/Rector/PhpDocReturnForIterableRector.php
> +            // the class reflection aboves takes also @method annotations into an account
```suggestion
            // The class reflection above takes also @method annotations into an account
```

2021-10-04 08:35 UTC, roman-eonx commented on tests/Rector/PhpDocReturnForIterableRector/Fixture/fixture3.php.inc
> +     * Another Custom Text that appear in the bottom
```suggestion
     * Another Custom Text that appears at the bottom
```

2021-10-04 08:35 UTC, roman-eonx commented on tests/Rector/PhpDocReturnForIterableRector/Fixture/fixture3.php.inc
> +     * Another Custom Text that appear in the bottom
```suggestion
     * Another Custom Text that appears at the bottom
```

2021-10-04 09:13 UTC, alexndlm commented on tests/Rector/PhpDocReturnForIterableRector/Fixture/fixture3.php.inc
> +     * Another Custom Text that appear in the bottom
Done.

2021-10-04 09:13 UTC, alexndlm commented on tests/Rector/PhpDocReturnForIterableRector/Fixture/fixture3.php.inc
> +     * Another Custom Text that appear in the bottom
Done

2021-10-04 09:13 UTC, alexndlm commented on src/Rector/PhpDocReturnForIterableRector.php
> +            // the class reflection aboves takes also @method annotations into an account
Done

2021-10-04 09:13 UTC, alexndlm commented on src/Rector/PhpDocReturnForIterableRector.php
> +            // possibly trait
Done

2021-10-04 09:20 UTC, roman-eonx approved these changes

2021-10-04 09:20 UTC, merged