Feature/plu 4060 add alphabetical sorting in class check
eonx-com/easy-quality pull request #23
Opened 2021-12-29 06:58 UTC by BOB41K1987

https://eonx.atlassian.net/browse/PLU-4060

2021-12-30 09:55 UTC, roman-eonx requested changes

2021-12-30 09:55 UTC, roman-eonx commented on src/Rector/SortConstAlphabeticallyRector.php
> +final class SortConstAlphabeticallyRector extends AbstractRector implements ConfigurableRectorInterface
Let's use the full plural word, as in other cases: `Const` -> `Constants`. The same goes for the ValueObject.

2021-12-30 14:32 UTC, alexndlm approved these changes

2022-01-10 05:41 UTC, BOB41K1987 commented on src/Rector/SortConstAlphabeticallyRector.php
> +final class SortConstAlphabeticallyRector extends AbstractRector implements ConfigurableRectorInterface
Done.

2022-01-10 07:39 UTC, roman-eonx approved these changes

2022-01-11 09:36 UTC, akl-95 requested changes

2022-01-11 09:36 UTC, akl-95 commented on src/Rector/EasyRankeable/ClassConstEasyRankeable.php
> +final class ClassConstEasyRankeable implements RankeableInterface
What about `ClassConstant...` instead to correspond the other class names?

2022-01-11 09:36 UTC, akl-95 commented on src/Rector/ValueObject/SortConstantsAlphabetically.php
> +    public function getRankeableCLass(): string
Pls fix typo `CL` -> `Cl`.

2022-01-11 09:37 UTC, ERuban requested changes

2022-01-11 09:37 UTC, ERuban commented on src/Rector/SortConstantsAlphabeticallyRector.php
> +        \uasort($rankeables,
Please, move `$rankeables` to the new line. Here and in other such places.

2022-01-17 09:04 UTC, BOB41K1987 commented on src/Rector/SortConstantsAlphabeticallyRector.php
> +        \uasort($rankeables,
Done.

2022-01-17 09:04 UTC, BOB41K1987 commented on src/Rector/ValueObject/SortConstantsAlphabetically.php
> +    public function getRankeableCLass(): string
Done.

2022-01-17 09:05 UTC, BOB41K1987 commented on src/Rector/EasyRankeable/ClassConstEasyRankeable.php
> +final class ClassConstEasyRankeable implements RankeableInterface
Fixed.

2022-01-17 09:34 UTC, ERuban approved these changes

2022-01-17 20:56 UTC, akl-95 approved these changes

2022-01-18 06:28 UTC, roman-eonx approved these changes

2022-01-18 06:28 UTC, merged