feature/PLU-4059-ecs-datetime-properties-declaration-check
eonx-com/easy-quality pull request #28
Opened 2022-03-20 10:57 UTC by alexandrtspl

* DoctrineColumnTypeSniff
* PropertyTypeSniff

https://eonx.atlassian.net/browse/PLU-4059

2022-03-22 13:07 UTC, alexndlm requested changes

2022-03-22 13:07 UTC, alexndlm commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +
Please remove empty lines.

2022-03-22 13:07 UTC, alexndlm commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +
Please remove empty lines.

2022-03-22 16:21 UTC, alexandrtspl commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +
Removed

2022-03-22 16:21 UTC, alexandrtspl commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +
Removed

2022-03-22 16:38 UTC, alexndlm commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +
thanks

2022-04-06 09:18 UTC, akl-95 requested changes

2022-04-06 09:18 UTC, akl-95 commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +final class DoctrineColumnTypeSniff implements Sniff
What about `DoctrineDateTimeColumnTypeSniff`?

2022-04-06 09:18 UTC, akl-95 commented on src/Sniffs/Classes/PropertyTypeSniff.php
> +final class PropertyTypeSniff extends AbstractVariableSniff
What about `DateTimePropertyTypeSniff`?

2022-04-06 09:18 UTC, akl-95 commented on tests/Sniffs/Attributes/DoctrineColumnTypeSniff/Fixture/Correct/correct.php.inc
> +<?php
Pls fix `Fixture` -> `Fixtures`.

2022-04-06 09:19 UTC, alexandrtspl commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +final class DoctrineColumnTypeSniff implements Sniff
We can use it not only for datetime

2022-04-06 09:19 UTC, alexandrtspl commented on src/Sniffs/Classes/PropertyTypeSniff.php
> +final class PropertyTypeSniff extends AbstractVariableSniff
Same as above. We can use it not only for datetime

2022-04-06 09:22 UTC, alexandrtspl commented on tests/Sniffs/Attributes/DoctrineColumnTypeSniff/Fixture/Correct/correct.php.inc
> +<?php
Fixed

2022-04-06 09:43 UTC, alexandrtspl commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +final class DoctrineColumnTypeSniff implements Sniff
Added another type to test

2022-04-06 09:43 UTC, alexandrtspl commented on src/Sniffs/Classes/PropertyTypeSniff.php
> +final class PropertyTypeSniff extends AbstractVariableSniff
Added another type to test

2022-04-06 13:22 UTC, roman-eonx requested changes

2022-04-06 14:27 UTC, alexandrtspl commented on src/Sniffs/Attributes/DoctrineColumnTypeSniff.php
> +declare(strict_types=1);
Added

2022-04-06 14:48 UTC, roman-eonx requested changes

2022-04-06 15:36 UTC, alexandrtspl commented on config/ecs/eonx-set.php
> +            'date' => 'date_immutable',
I don't think so. Because it's a config for all. 
Maybe someone doesn't use Types class and uses "strings". That's why "strings" was replaced with "strings".

But if you insist I will add it.

2022-04-07 05:54 UTC, roman-eonx commented on config/ecs/eonx-set.php
> +            'date' => 'date_immutable',
This EonX set is needed to force the standards in all our projects. Even if there is a reason to not replace all the types, a project can override this config easily.
Let's make this default config ready to use for all our projects by enumerating all the possible types.

2022-04-07 07:34 UTC, alexandrtspl commented on config/ecs/eonx-set.php
> +            'date' => 'date_immutable',
Done

2022-04-07 09:53 UTC, roman-eonx approved these changes

2022-04-07 10:20 UTC, akl-95 requested changes

2022-04-07 10:20 UTC, akl-95 commented on config/ecs/eonx-set.php
> +            'array' => 'Types::ARRAY',
Now we duplicate the responsibility of `AttributeKeyToClassConstFetchRector`. Seems we can remove this rector now.

2022-04-07 10:31 UTC, roman-eonx commented on config/ecs/eonx-set.php
> +            'array' => 'Types::ARRAY',
We use `AttributeKeyToClassConstFetchRector` on the project level and not in the set. So, it's up to the project to keep it or not. And `AttributeKeyToClassConstFetchRector` also allows us to set the `JSONB` mapping (or any other custom types), so it looks like a more flexible solution.

Maybe we should keep using `AttributeKeyToClassConstFetchRector` in projects and configure `DoctrineColumnTypeSniff` to keep an eye on date/dateime types only then (as it was before, without constants, to not do the rector's job)? Sorry, I forgot about this rector, so if you agree with this, we should revert the latest changes.

2022-04-07 10:34 UTC, akl-95 commented on config/ecs/eonx-set.php
> +            'array' => 'Types::ARRAY',
Yep, I think it would be the better option to have sniffs only for datetimes and only for changing to `immutable` with no responsibility about using consts instead of type strings.

2022-04-07 11:05 UTC, roman-eonx approved these changes

2022-04-07 11:08 UTC, akl-95 approved these changes

2022-04-07 11:48 UTC, merged