feature/Add-custom-ReturnArrayClassMethodToYieldRector
eonx-com/easy-quality pull request #3
Opened 2021-08-09 11:08 UTC by alexndlm

Added ReturnArrayClassMethodToYieldRector which works correctly with comments and adds an iterable return type

2021-08-09 14:44 UTC, ERuban requested changes

2021-08-09 15:17 UTC, alexndlm commented on tests/Rector/ReturnArrayClassMethodToYieldRector/Fixture/data_provider.php.inc
> +     * @return mixed[]
I'm try did this in many different ways, but haven't luck :(

2021-08-09 16:10 UTC, alexndlm commented on tests/Rector/ReturnArrayClassMethodToYieldRector/Fixture/fixture.php.inc
> +{
It seems to me that a complete implementation with all variations would be redundant at this stage.

At now I can simple `yield $array;` and edit the rest manually.

2021-08-10 12:15 UTC, ERuban approved these changes

2021-08-10 12:16 UTC, alexndlm commented on tests/Rector/ReturnArrayClassMethodToYieldRector/Fixture/data_provider.php.inc
> +     * @return mixed[]
Done, thanks for idea discussed in Slack

2021-08-10 12:16 UTC, alexndlm commented on tests/Rector/ReturnArrayClassMethodToYieldRector/Fixture/fixture.php.inc
> +{
Done partly for the `rector` to highlight these sections of the code.

2021-08-11 06:39 UTC, roman-eonx requested changes

2021-08-11 06:39 UTC, roman-eonx commented on docs/ecs/sniffs.md
> +Checks that using `yield` instead `return` in a specified classes and methods.
```suggestion
Checks that `yield` is used instead of `return` in specified classes and methods.
```

2021-08-11 06:39 UTC, roman-eonx commented on docs/ecs/sniffs.md
> +- `applyTo` - An array of regular expressions to match method names. Format.
```suggestion
- `applyTo` - An array of regular expressions to match the class namespace and method name. Example:
```

2021-08-11 06:39 UTC, roman-eonx commented on docs/ecs/settings.md
> +use EonX\EasyQuality\Sniffs\Methods\UseYieldInsteadReturnSniff;
Please rename the sniff to `UseYieldInsteadOfReturnSniff`.

2021-08-11 06:55 UTC, alexndlm commented on docs/ecs/sniffs.md
> +Checks that using `yield` instead `return` in a specified classes and methods.
Done

2021-08-11 06:55 UTC, alexndlm commented on docs/ecs/sniffs.md
> +- `applyTo` - An array of regular expressions to match method names. Format.
Done

2021-08-11 06:55 UTC, alexndlm commented on docs/ecs/settings.md
> +use EonX\EasyQuality\Sniffs\Methods\UseYieldInsteadReturnSniff;
Done

2021-08-11 07:42 UTC, roman-eonx commented on docs/ecs/settings.md
> +use EonX\EasyQuality\Sniffs\Methods\UseYieldInsteadReturnSniff;
One more place left: `tests/Sniffs/Methods/UseYieldInsteadOfReturnSniff/UseYieldInsteadReturnSniffTest.php`.

2021-08-11 07:47 UTC, akl-95 requested changes

2021-08-11 10:24 UTC, alexndlm commented on docs/ecs/settings.md
> +use EonX\EasyQuality\Sniffs\Methods\UseYieldInsteadReturnSniff;
Oops, done.

2021-08-11 10:24 UTC, alexndlm commented on src/Sniffs/Methods/UseYieldInsteadOfReturnSniff.php
> +class UseYieldInsteadOfReturnSniff implements Sniff
Done.

2021-08-11 10:24 UTC, alexndlm commented on docs/rectors/rectors.md
> +Turns array return to yield return in specified classes and methods.
Done.

2021-08-11 10:25 UTC, alexndlm commented on docs/rectors/rectors.md
> +    /**
This rector adds a dockblock.

2021-08-11 10:41 UTC, alexndlm commented on docs/rectors/rectors.md
> +##### [\EonX\EasyQuality\Rector\ReturnArrayClassMethodToYieldRector][8]
I took the name of the original rector. And I agree, you can change it, so there will be a clear difference.
Done.

2021-08-11 11:47 UTC, roman-eonx approved these changes

2021-08-11 14:17 UTC, akl-95 approved these changes

2021-08-11 14:35 UTC, merged