hotfix/throw-exception-message-rule-static-call
eonx-com/easy-quality pull request #32
Opened 2022-04-20 08:29 UTC by alexandrtspl

* remove check in static calls

2022-04-20 10:32 UTC, ERuban requested changes

2022-04-20 10:32 UTC, ERuban commented on src/PHPStan/ThrowExceptionMessageRule.php
> +}
Please, add an empty line at the end of file. Here and in others.

2022-04-20 10:32 UTC, ERuban commented on tests/PHPStan/ThrowExceptionMessageRule/Fixture/correct/staticCall.php.inc
> +throw LogicException::exception('some-parameter');
Let's add one more example with a standard method call: `LogicException->exception('some-parameter')`

2022-04-20 10:46 UTC, alexandrtspl commented on src/PHPStan/ThrowExceptionMessageRule.php
> +}
Added

2022-04-20 10:47 UTC, ERuban approved these changes

2022-04-20 12:05 UTC, alexndlm approved these changes

2022-04-20 12:25 UTC, akl-95 approved these changes

2022-04-21 12:46 UTC, itorgov approved these changes

2022-04-25 08:50 UTC, roman-eonx approved these changes

2022-04-25 08:50 UTC, merged