feature/PLU-4180-sort-api-resource-operations
eonx-com/easy-quality pull request #33
Opened 2022-05-20 07:22 UTC by alexandrtspl

* sort ApiResourceOperations

2022-05-20 19:09 UTC, ERuban requested changes

2022-05-20 19:09 UTC, ERuban commented on config/rector/eonx-set.php
> +    $services->set(SortApiResourceOperationsRector::class)->call('configure', [
Not sure that we need it in main set.
Not all projects that uses this set works with api-platform - as example Points_v1 (https://github.com/eonx-com/points-api-v1/blob/release/src/rector.php)

2022-05-20 19:09 UTC, ERuban commented on tests/Rector/SortApiResourceOperationsRector/Fixture/ApiResourceOperationsSorted.php.inc
> +}
Please, add empty line at the and of the class.

2022-05-20 19:09 UTC, ERuban commented on src/Rector/EasyRankeable/ApiResourceOperationEasyRankeable.php
> +            $this->getName() !== 'get',
Why those standard operations sorted like this (not-alphabetically)?
And also do we really need those `activate` and `deactivate` operations to be on the top of other non-standard operations?

2022-05-23 03:29 UTC, alexandrtspl commented on config/rector/eonx-set.php
> +    $services->set(SortApiResourceOperationsRector::class)->call('configure', [
I'm agreed. Removed

2022-05-23 03:35 UTC, alexandrtspl commented on tests/Rector/SortApiResourceOperationsRector/Fixture/ApiResourceOperationsSorted.php.inc
> +}
Added

2022-05-23 13:47 UTC, ERuban approved these changes

2022-06-02 07:19 UTC, akl-95 approved these changes

2022-06-09 08:25 UTC, closed without merging