Update slevomat/coding-standard and rector
eonx-com/easy-quality pull request #35
Opened 2022-05-20 15:19 UTC by alexndlm

2022-05-24 12:00 UTC, roman-eonx requested changes
- Let's also update PHPStan to the latest release, as there are many improvements in 1.7.x.
- Let's update Rector to the latest release (0.13.x).

2022-05-27 17:53 UTC, alexndlm commented
> * Let's also update PHPStan to the latest release, as there are many improvements in 1.7.x.
> * Let's update Rector to the latest release (0.13.x).

Have done.

2022-06-14 08:36 UTC, roman-eonx requested changes

2022-06-14 08:36 UTC, roman-eonx commented on src/Rector/PhpDocCommentRector.php
> +        // We need generate new text without * for compare.
Please update the comment:
```
// We need to generate new text without "*" for comparison
```

2022-06-14 08:38 UTC, alexndlm commented on src/Rector/PhpDocCommentRector.php
> +        // We need generate new text without * for compare.
Have done

2022-06-14 09:19 UTC, alexndlm commented on src/Rector/SingleLineCommentRector.php
> +                $pattern = '#' . \preg_quote($disallowEnding, '#') . '$#';
If you talking about my change:
<img width="1440" alt="Снимок экрана 2022-06-14 в 11 18 07" src="https://user-images.githubusercontent.com/6824784/173542492-34a36bf4-969b-485f-a413-6a88a3a328e3.png">

2022-06-14 09:19 UTC, akl-95 approved these changes

2022-06-14 09:30 UTC, ERuban approved these changes

2022-06-14 09:35 UTC, merged