[ECS] Add applyTo option to AvoidPrivatePropertiesSniff
eonx-com/easy-quality pull request #43
Opened 2022-09-08 15:44 UTC by alexndlm

Recently Tomas dropped `only` option in skipper - https://github.com/symplify/symplify/pull/4376

I have found that more ease way for us is to update `AvoidPrivatePropertiesSniff `

2022-09-09 06:51 UTC, roman-eonx requested changes

2022-09-09 06:51 UTC, roman-eonx commented on tests/Sniffs/Classes/AvoidPrivatePropertiesSniff/Fixture/MissedScopeProperties.php.inc
> +$myProperty;
Why did you remove the indent?

2022-09-09 07:16 UTC, alexndlm commented on tests/Sniffs/Classes/AvoidPrivatePropertiesSniff/Fixture/MissedScopeProperties.php.inc
> +$myProperty;
Automating .....

Fixed

2022-09-18 17:59 UTC, alexndlm commented
We decided to deprecate this sniff

2022-09-18 17:59 UTC, closed without merging