-add SortAttributesAlphabeticallySniff
eonx-com/easy-quality pull request #54
Opened 2022-11-17 16:55 UTC by alexndlm

`AttributesOrderSniff` from `slevomat/coding-standard` is not suitable for us.

Package owner decides that alphabetical sorting with attribute content is bad - https://github.com/slevomat/coding-standard/pull/1461#issuecomment-1315290602

2022-11-17 17:29 UTC, ERuban requested changes

2022-11-17 17:29 UTC, ERuban commented on docs/ecs/sniffs.md
> +    'string' => 'Types::STRING',
`Types::STRING` seems to be without `'`

2022-11-17 17:29 UTC, ERuban commented on docs/ecs/sniffs.md
> +**Configuration**
This configuration seems not for this sniff. It is from the sniff above.

2022-11-17 17:57 UTC, alexndlm commented on docs/ecs/sniffs.md
> +    'string' => 'Types::STRING',
Fixed.

2022-11-17 17:57 UTC, alexndlm commented on docs/ecs/sniffs.md
> +**Configuration**
Copy paste :(

Fixed.

2022-11-17 17:59 UTC, alexndlm commented on tests/Sniffs/AbstractSniffTestCase.php
> +abstract class AbstractSniffTestCase extends \PHPUnit\Framework\TestCase
I have copied this test case from `SlevomatCodingStandard/Sniffs/TestCase.php`.

It is better than the current approach because we can test if a sniff correctly changes a file.

2022-11-17 18:03 UTC, ERuban requested changes

2022-11-17 18:03 UTC, ERuban commented on tests/Sniffs/AbstractSniffTestCase.php
> +abstract class AbstractSniffTestCase extends \PHPUnit\Framework\TestCase
Please, import `TestCase` using `use`)

2022-11-17 18:21 UTC, ERuban approved these changes

2022-11-17 18:21 UTC, ERuban commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> +            } else {
`else`?)

2022-11-18 06:46 UTC, roman-eonx requested changes

2022-11-18 06:46 UTC, roman-eonx commented on docs/ecs/sniffs.md
> -[1]: https://github.com/eonx-com/easy-quality/blob/main/src/Sniffs/Arrays/AlphabeticallySortedArrayKeysSniff.php
Why did you remove links?

2022-11-18 08:21 UTC, akl-95 requested changes

2022-11-18 08:21 UTC, akl-95 commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> + * @noinspection PhpInternalEntityUsedInspection
Why do we need it and why it's placed in that strange place (before `declare` I mean)?

2022-11-18 08:21 UTC, akl-95 commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> +class SortAttributesAlphabeticallySniff implements Sniff
Why not final?

2022-11-18 08:21 UTC, akl-95 commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> +    public const CODE_INCORRECT_ORDER = 'IncorrectOrder';
Can we make it private?

2022-12-08 09:34 UTC, alexndlm commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> + * @noinspection PhpInternalEntityUsedInspection
Removed.

2022-12-08 09:34 UTC, alexndlm commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> +class SortAttributesAlphabeticallySniff implements Sniff
Fixed

2022-12-08 09:34 UTC, alexndlm commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> +    public const CODE_INCORRECT_ORDER = 'IncorrectOrder';
Done

2022-12-08 09:34 UTC, alexndlm commented on src/Sniffs/Attributes/SortAttributesAlphabeticallySniff.php
> +            } else {
Fixed.

2022-12-08 10:53 UTC, roman-eonx approved these changes

2022-12-08 10:55 UTC, ERuban approved these changes

2022-12-08 11:42 UTC, akl-95 approved these changes

2022-12-08 13:58 UTC, merged