Setup Rector checks
eonx-com/easy-quality pull request #59
Opened 2022-11-21 11:30 UTC by alexndlm

2022-11-22 13:30 UTC, ERuban approved these changes

2022-11-23 07:48 UTC, roman-eonx requested changes

2022-11-23 07:48 UTC, roman-eonx commented on composer.json
> +  "name": "eonx-com/easy-quality",
Please revert the indents.

2022-11-23 07:48 UTC, roman-eonx commented on src/PHPStan/ThrowExceptionMessageRule.php
> +    public function __construct(private readonly ?string $exceptionInterface = null, ?array $validPrefixes = null)
Why not promote the second property as well? If I remember correctly, we allow default values in constructors.

2022-11-23 07:48 UTC, roman-eonx commented on src/Rector/PhpDocCommentRector.php
>                  $lastLetter = Strings::substring($value->value, -1, 1);
Can we replace this with a built-in function and get rid of `Strings` completely? Here and in other rector classes.

2022-11-23 07:48 UTC, roman-eonx commented on src/Sniffs/Classes/AvoidPublicPropertiesSniff.php
> +        // No needed for sniff
Please change to `Not needed`. Here and below.

2022-11-23 07:48 UTC, roman-eonx commented on src/Sniffs/Commenting/FunctionCommentSniff.php
> +/**
This comment is obsolete, let's get rid of it.

2022-11-23 07:48 UTC, roman-eonx commented on src/Sniffs/Commenting/FunctionCommentSniff.php
>                          // $error = 'Missing parameter comment';
Let's get rid of the dead code.

2022-11-23 07:48 UTC, roman-eonx commented on src/Sniffs/Commenting/FunctionCommentSniff.php
> +                    }// End if
Let's remove all such useless comments.

2022-11-23 12:57 UTC, alexndlm commented on src/PHPStan/ThrowExceptionMessageRule.php
> +    public function __construct(private readonly ?string $exceptionInterface = null, ?array $validPrefixes = null)
Super! Thanks! Done!

2022-11-23 13:26 UTC, alexndlm commented on src/Rector/PhpDocCommentRector.php
>                  $lastLetter = Strings::substring($value->value, -1, 1);
With joy.

Done.

2022-11-23 13:26 UTC, alexndlm commented on src/Sniffs/Classes/AvoidPublicPropertiesSniff.php
> +        // No needed for sniff
Done.

2022-11-23 13:27 UTC, alexndlm commented on src/Sniffs/Commenting/FunctionCommentSniff.php
> +/**
Done.

2022-11-23 13:29 UTC, alexndlm commented on src/Sniffs/Commenting/FunctionCommentSniff.php
>                          // $error = 'Missing parameter comment';
Done.

2022-11-23 13:29 UTC, alexndlm commented on src/Sniffs/Commenting/FunctionCommentSniff.php
> +                    }// End if
Done.

2022-11-23 13:29 UTC, alexndlm commented on composer.json
> +  "name": "eonx-com/easy-quality",
Thanks. Fixed

2022-11-23 15:01 UTC, roman-eonx commented on src/Sniffs/Commenting/FunctionCommentSniff.php
>                          // $error = 'Missing parameter comment';
All the commented code lines in this file, please.

2022-11-23 15:02 UTC, roman-eonx commented on src/Sniffs/Commenting/FunctionCommentSniff.php
> +                    }// End if
At least one more left.

2022-11-23 15:09 UTC, alexndlm commented on src/Sniffs/Commenting/FunctionCommentSniff.php
> +                    }// End if
Sorry, I have rechecked and fixed all.

2022-11-23 15:09 UTC, alexndlm commented on src/Sniffs/Commenting/FunctionCommentSniff.php
>                          // $error = 'Missing parameter comment';
Sorry, I have rechecked and fixed all.

2022-11-24 06:16 UTC, roman-eonx approved these changes

2022-11-24 06:17 UTC, merged