feature/add-MakeClassAbstractSniff
eonx-com/easy-quality pull request #6
Opened 2021-09-08 16:41 UTC by alexndlm

2021-09-09 10:15 UTC, roman-eonx requested changes

2021-09-09 10:15 UTC, roman-eonx commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +class MakeClassAbstractSniff implements Sniff
Please add this new sniff to the docs with an example of applying it to TestCase classes.

2021-09-09 11:16 UTC, ERuban requested changes

2021-09-09 11:16 UTC, ERuban commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +    public function process(File $phpcsFile, $clasPointer): void
`$classPointer`

2021-09-09 11:16 UTC, ERuban commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +     * @param \PHP_CodeSniffer\Files\File $phpcsFile The file being scanned.
Not needed

2021-09-09 11:16 UTC, ERuban commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +     * @return void
Not needed

2021-09-09 11:16 UTC, ERuban commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +     * @param string $classFqn
Not needed

2021-09-09 11:20 UTC, ERuban commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +    public function process(File $phpcsFile, $clasPointer): void
Also, usually this parameter named as `$stackPtr`

2021-09-09 11:23 UTC, ERuban requested changes

2021-09-09 11:23 UTC, ERuban commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +     * @param \PHP_CodeSniffer\Files\File $phpcsFile The file being scanned.
I think we can get rid of these phpdocs as we already have it in the parent class

2021-09-10 08:09 UTC, alexndlm commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +class MakeClassAbstractSniff implements Sniff
Done.

2021-09-10 08:10 UTC, alexndlm commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +    public function process(File $phpcsFile, $clasPointer): void
Done.

2021-09-10 08:10 UTC, alexndlm commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +     * @param \PHP_CodeSniffer\Files\File $phpcsFile The file being scanned.
Done.

2021-09-10 08:10 UTC, alexndlm commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +     * @return void
Done.

2021-09-10 08:10 UTC, alexndlm commented on src/Sniffs/Classes/MakeClassAbstractSniff.php
> +     * @param string $classFqn
Done.

2021-09-10 11:53 UTC, roman-eonx approved these changes

2021-09-10 13:53 UTC, ERuban approved these changes

2021-09-13 12:10 UTC, merged