feature/upgrade-all-packages-15-05-2023
eonx-com/easy-quality pull request #63
Opened 2023-05-16 07:28 UTC by alexndlm

2023-05-16 07:29 UTC, alexndlm commented on src/Rector/InheritDocRector.php
> +            if ($child->getAttribute('orig_node') . '' === self::INHERITDOC_INCORRECT_ANNOTATION) {
Due to https://github.com/phpstan/phpstan/issues/9295

2023-05-16 07:30 UTC, alexndlm commented on tests/Sniffs/Namespaces/Psr4Sniff/Psr4SniffTest.php
> -    public function testSniff(SmartFileInfo $smartFileInfo, int $expectedErrorCount): void
This test was not worked before. Due to specific sniff implementation, we need a special test.

2023-05-16 08:44 UTC, roman-eonx requested changes

2023-05-16 08:44 UTC, roman-eonx commented on ecs.php
> +            'tests/*',
Why do we want to ignore the whole dir?

2023-05-16 08:44 UTC, roman-eonx commented on src/Rector/InheritDocRector.php
> +            if ($child->getAttribute('orig_node') . '' === self::INHERITDOC_INCORRECT_ANNOTATION) {
I don't really like the current solution. Do we have other options? Does casting to string work?

2023-05-16 08:59 UTC, alexndlm commented on ecs.php
> +            'tests/*',
Primarily due to `dataProvider`. We do this for all other projects.

2023-05-16 09:02 UTC, alexndlm commented on src/Rector/InheritDocRector.php
> +            if ($child->getAttribute('orig_node') . '' === self::INHERITDOC_INCORRECT_ANNOTATION) {
No :( 
Casting and `strval` do not work.

2023-05-16 09:04 UTC, roman-eonx commented on src/Rector/InheritDocRector.php
> +            if ($child->getAttribute('orig_node') . '' === self::INHERITDOC_INCORRECT_ANNOTATION) {
Let's discuss this with the team then. Writing `. ''` and `* 1` everywhere will not make our code easier to read.

2023-05-16 09:14 UTC, alexndlm commented on src/Rector/InheritDocRector.php
> +            if ($child->getAttribute('orig_node') . '' === self::INHERITDOC_INCORRECT_ANNOTATION) {
I have refactored. Please check.

2023-05-18 09:21 UTC, roman-eonx approved these changes

2023-05-18 11:44 UTC, alexndlm commented on tests/Sniffs/AbstractSniffTestCase.php
> +            $this->fail('No fixers nor sniffers were found. Registers them in your config.');
Fixed

2023-05-18 11:45 UTC, ERuban approved these changes

2023-05-18 12:59 UTC, merged