feature/Add-DisallowBusinessConstantUsageInAssertBlock-sniff
eonx-com/easy-quality pull request #64
Opened 2023-05-16 15:12 UTC by BOB41K1987

- Add DisallowBusinessConstantUsageInAssertBlock sniff

2023-05-17 10:58 UTC, alexndlm requested changes

2023-05-17 10:58 UTC, alexndlm commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +{
What about adding an option to disable using const in `arrange` and `act` blocks and in `dataProviders`?

2023-05-17 10:58 UTC, alexndlm commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +     * @var string
Let's drop all stuff like this. In repo, we have php `8.1`

2023-05-17 17:42 UTC, akl-95 commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +final class DisallowBusinessConstantUsageInAssertBlock implements Sniff
Another idea is to use `Application` instead of `Business`.

2023-05-17 17:49 UTC, akl-95 requested changes

2023-05-17 17:49 UTC, akl-95 commented on docs/ecs/sniffs.md
> +Disallow business constant and enums usage in assert block of the tests.
Please fix `Disallow` -> `Disallows`.

2023-05-17 17:49 UTC, akl-95 commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +                    "Method [{$method}] uses business constant {$previousToken['content']}::" .
What about `constant` -> `constant/enum`?

2023-05-18 01:16 UTC, BOB41K1987 commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +{
We don't have such rules so I don't think we need them. Regarding `dataProviders`, it's hard to determine in which block we use provided values.

2023-05-18 01:16 UTC, BOB41K1987 commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +     * @var string
Done, thanks.

2023-05-18 01:16 UTC, BOB41K1987 commented on docs/ecs/sniffs.md
> +Disallow business constant and enums usage in assert block of the tests.
Done, thanks.

2023-05-18 08:03 UTC, akl-95 approved these changes

2023-05-18 08:59 UTC, alexndlm commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +final class DisallowBusinessConstantUsageInAssertBlock implements Sniff
Thanks

2023-05-18 08:59 UTC, alexndlm commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +{
Ok, maybe we'll come back to this in the future.

2023-05-18 08:59 UTC, alexndlm commented on src/Sniffs/Constants/DisallowBusinessConstantUsageInAssertBlock.php
> +     * @var string
Thanks

2023-05-18 09:00 UTC, alexndlm approved these changes

2023-05-18 11:22 UTC, ERuban requested changes

2023-05-18 11:22 UTC, ERuban commented on tests/Sniffs/Constants/DisallowApplicationConstantAndEnumUsageInTestAssertBlock/Fixture/Correct/SelfUsage.php.inc
> +<?php
Let's add one more correct case - for the test method with just two blocks - `act` and `assert`

2023-05-18 11:44 UTC, BOB41K1987 commented on tests/Sniffs/Constants/DisallowApplicationConstantAndEnumUsageInTestAssertBlock/Fixture/Correct/SelfUsage.php.inc
> +<?php
Done.

2023-05-18 11:45 UTC, ERuban approved these changes

2023-05-18 12:27 UTC, roman-eonx approved these changes

2023-05-18 12:27 UTC, merged