[ECS] Refactor sniffs to not show extra errors
eonx-com/easy-quality pull request #67
Opened 2023-05-18 13:35 UTC by alexndlm

- it is no sense to add text error if we provide fixable error

2023-05-18 13:57 UTC, ERuban requested changes

2023-05-18 13:57 UTC, ERuban commented on tests/Sniffs/Namespaces/Psr4Sniff/Fixture/Wrong/NamespaceWithSingleWorld.php.inc
> +class NamespaceWithSingleWorld
`NamespaceWithSingleWorld` => `SingleWordNamespace` looks better, imo

2023-05-18 13:57 UTC, ERuban commented on tests/Sniffs/Namespaces/Psr4Sniff/Psr4SniffTest.php
> +        yield 'Wrong, namespace with single world' => [
`word`

2023-05-18 13:58 UTC, ERuban commented
Don't we need to fix `AlphabeticallySortedArrayKeysSniff` too?

2023-05-18 14:00 UTC, alexndlm commented on tests/Sniffs/Namespaces/Psr4Sniff/Fixture/Wrong/NamespaceWithSingleWorld.php.inc
> +class NamespaceWithSingleWorld
Thanks. Fixed.

2023-05-18 14:00 UTC, alexndlm commented on tests/Sniffs/Namespaces/Psr4Sniff/Psr4SniffTest.php
> +        yield 'Wrong, namespace with single world' => [
Thanks. Fixed.

2023-05-18 16:09 UTC, alexndlm commented
> Don't we need to fix `AlphabeticallySortedArrayKeysSniff` too?

Thanks. Great point. Fixed.

2023-05-18 16:55 UTC, ERuban approved these changes

2023-05-18 23:07 UTC, ERuban commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
> -        $phpcsFile->addErrorOnLine(
Not related to that PR - please, add the description that this sniff applicable to `api-platform` usage only.
Thank you 🙏

2023-05-18 23:09 UTC, ERuban commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
> -        $phpcsFile->addErrorOnLine(
Actually we can get rid of this then, bcs it is actual only for >=2.7 versions of the api-platform

2023-05-19 10:40 UTC, alexndlm commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
> -        $phpcsFile->addErrorOnLine(
Done

2023-05-19 11:13 UTC, roman-eonx approved these changes

2023-05-19 11:14 UTC, merged