[ECS] Use value when key is-null in AlphabeticallySortedArrayKeysSniff
eonx-com/easy-quality pull request #68
Opened 2023-05-18 16:46 UTC by alexndlm

2023-05-18 16:51 UTC, ERuban requested changes

2023-05-18 16:51 UTC, ERuban commented on tests/Sniffs/Arrays/AlphabeticallySortedArrayKeysSniff/Fixture/Wrong/MultiLineArray.php.inc
>      'a' => 1,
Don't like this idea at all. The result looks weird. Not sure that it is a good idea to mix keys and values as a source for sorting.

2023-05-18 16:52 UTC, ERuban commented on src/Sniffs/Arrays/AlphabeticallySortedArrayKeysSniff.php
> -        $phpcsFile->addErrorOnLine(
Let's fix it in the related PR (I have a comment about it there) ;)

2023-05-18 16:59 UTC, alexndlm commented on tests/Sniffs/Arrays/AlphabeticallySortedArrayKeysSniff/Fixture/Wrong/MultiLineArray.php.inc
>      'a' => 1,
This is more useful.

We must do strange things to have a proper ordering.

We can't use this sniff in tests because it sorts response structure arrays weirdly.
<img width="1440" alt="Снимок экрана 2023-05-18 в 18 56 43" src="https://github.com/eonx-com/easy-quality/assets/6824784/42fc4d54-86c9-4dc3-90bf-02d8f6b55004">

2023-05-19 10:30 UTC, alexndlm commented
We decided to create a new sniff

2023-05-19 10:30 UTC, closed without merging