feature/PLU-3385-regexp-in-sniffer
eonx-com/easy-quality pull request #7
Opened 2021-09-13 11:56 UTC by voodooism

-Added an opportunity to set namespaces in "annotationsGroups" property by mask

2021-09-14 14:05 UTC, alexndlm commented on src/Sniffs/Commenting/DocCommentSpacingSniff.php
> +    private function checkAnnotationsGroupsOrder(
Can we remove this function from here?

2021-09-14 14:05 UTC, alexndlm commented on src/Sniffs/Commenting/DocCommentSpacingSniff.php
> +    private function checkLinesAfterLastContent(
Can we remove this function from here?

2021-09-14 14:05 UTC, alexndlm commented on src/Sniffs/Commenting/DocCommentSpacingSniff.php
> +    private function getAnnotationsGroups(): array
Can we remove this function from here?

2021-09-14 14:05 UTC, alexndlm commented on tests/Sniffs/Commenting/DocCommentSpacingSniff/config/configured_rule.php
> +            '@AppAssert*',
Let's add regex support.

2021-09-14 14:48 UTC, voodooism commented on tests/Sniffs/Commenting/DocCommentSpacingSniff/config/configured_rule.php
> +            '@AppAssert*',
As I remember, we decided to implement only mask on the Friday call

2021-09-14 16:29 UTC, voodooism commented on src/Sniffs/Commenting/DocCommentSpacingSniff.php
> +    private $normalizedAnnotationsGroups = null;
Here and below: unfortunately all the methods in Slevomat\DocCommentSpacingSniff are private. I think we can use reflection, but I'm not sure that it would be the best solution.

I've also opened PR in the Slevomat repository https://github.com/slevomat/coding-standard/pull/1277

2021-09-14 18:05 UTC, voodooism commented on src/Sniffs/Commenting/DocCommentSpacingSniff.php
> +    public function process(File $phpcsFile, $docCommentOpenerPointer): void
Definitely not, because it is an implementation of the `Sniff` interface

2021-09-14 19:10 UTC, ERuban approved these changes

2021-09-14 19:13 UTC, ERuban requested changes

2021-09-14 19:13 UTC, ERuban commented on tests/Sniffs/Commenting/DocCommentSpacingSniff/Fixtures/Correct/DocCommentSpacingSniffTest.php.inc
> +}
please, add an empty line at the of the file

2021-09-14 19:13 UTC, ERuban commented on tests/Sniffs/Commenting/DocCommentSpacingSniff/Fixtures/Wrong/DocCommentSpacingSniffTest.php.inc
> +}
please, add an empty line at the of the file

2021-09-15 06:14 UTC, voodooism commented on tests/Sniffs/Commenting/DocCommentSpacingSniff/Fixtures/Correct/DocCommentSpacingSniffTest.php.inc
> +}
done

2021-09-15 06:15 UTC, voodooism commented on tests/Sniffs/Commenting/DocCommentSpacingSniff/Fixtures/Wrong/DocCommentSpacingSniffTest.php.inc
> +}
done

2021-09-15 07:00 UTC, alexndlm commented on src/Sniffs/Commenting/DocCommentSpacingSniff.php
> +    private $normalizedAnnotationsGroups = null;
Clear. Thanks.

2021-09-15 07:01 UTC, alexndlm commented on tests/Sniffs/Commenting/DocCommentSpacingSniff/config/configured_rule.php
> +            '@AppAssert*',
Ok

2021-09-15 10:56 UTC, ERuban approved these changes

2021-09-15 15:25 UTC, alexndlm approved these changes

2021-09-15 15:53 UTC, roman-eonx approved these changes

2021-09-15 15:54 UTC, merged