Feature/use phpmetrics
eonx-com/easy-quality pull request #79
Opened 2023-07-07 15:54 UTC by ERuban

2023-07-13 17:08 UTC, roman-eonx requested changes

2023-07-13 17:08 UTC, roman-eonx commented on src/PhpMetricsChecker/Metric/CcnMethodMax.php
> +final class CcnMethodMax extends AbstractMetric
It's not obvious what `Ccn` means. Let's rename this class (and change the `NAME` value accordingly) to `CyclomaticComplexity`.

2023-07-13 17:08 UTC, roman-eonx commented on src/PhpMetricsChecker/Search/SearchesFactory.php
> +final class SearchesFactory
Does this `Factory` term come from the PhpMetrics library? Seeing the `build` method below, I'd suggest either renaming the class to `SearchesBuilder` or the method to `create`.

2023-07-14 13:03 UTC, ERuban commented on composer.json
> +        "phpmetrics/phpmetrics": "^2.8"
done

2023-07-14 13:03 UTC, ERuban commented on src/PhpMetricsChecker/Metric/CcnMethodMax.php
> +final class CcnMethodMax extends AbstractMetric
done

2023-07-14 13:04 UTC, ERuban commented on src/PhpMetricsChecker/Search/SearchesFactory.php
> +final class SearchesFactory
Yes, Factory term is from `phpmetrics` library. And the method name in it is `factory()`. So have renamed the method name to `factory()` to me maximum consistent with phpmetrics

2023-07-18 09:21 UTC, itorgov commented on bin/pmc
> +error_reporting(error_reporting() & ~E_DEPRECATED);
Please add `declare(strict_types=1);`.

2023-07-18 09:26 UTC, itorgov commented on bin/pmc
> +        return include $file;
Can we use the `require_once` operator instead?

2023-07-18 09:30 UTC, itorgov commented on src/PhpMetricsChecker/Config/ConfigFileReader.php
> +        $jsonData = \json_decode($jsonText, true, 512, \JSON_THROW_ON_ERROR);
Let's use named arguments to skip the `depth` value:

```php
\json_decode(json: $jsonText, associative: true, flags: \JSON_THROW_ON_ERROR)
```

2023-07-18 10:57 UTC, ERuban commented on bin/pmc
> +error_reporting(error_reporting() & ~E_DEPRECATED);
done

2023-07-18 10:57 UTC, ERuban commented on src/PhpMetricsChecker/Config/ConfigFileReader.php
> +        $jsonData = \json_decode($jsonText, true, 512, \JSON_THROW_ON_ERROR);
done

2023-07-18 10:58 UTC, ERuban commented on bin/pmc
> +        return include $file;
No, we cannot.
`[EA] Only the first call returns the proper/expected result. Subsequent calls will return 'true'.`

2023-07-18 11:06 UTC, itorgov approved these changes

2023-07-18 11:17 UTC, roman-eonx approved these changes

2023-07-18 11:17 UTC, merged