feature/PBA-3528-Add-a-new-check-for-grants-query-in-the-create-table…
eonx-com/easy-quality pull request #83
Opened 2023-10-10 16:04 UTC by BOB41K1987

https://eonx.atlassian.net/browse/PBA-3528

2023-10-19 11:23 UTC, alexndlm requested changes

2023-10-19 11:23 UTC, alexndlm commented on tests/Sniffs/Migrations/GrantsForCreateTableMigrationSniff/Fixture/Wrong/MigrationWithCreateTableWithoutGrant.php
> +    public function migrate(): void
Let's add a case when create `table1` and grant permission for `table2`.

2023-10-19 23:19 UTC, egor-dev requested changes

2023-10-19 23:19 UTC, egor-dev commented on src/Sniffs/Migrations/GrantsForCreateTableMigrationSniff.php
> +final class GrantsForCreateTableMigrationSniff implements Sniff
If you look at migrations in Transact and Identity, you will see that many migrations in the beginning are without grants. It's because that rule was enforced not from the start. Do I get it right that we will be able to configure skipping like that
```
GrantsForCreateTableMigrationSniff::class => [
    'src/migrations/Version20211109095633.php',
    'src/migrations/Version20211118105529.php',
    ...
],
```
?

2023-11-07 10:05 UTC, BOB41K1987 commented on src/Sniffs/Migrations/GrantsForCreateTableMigrationSniff.php
> +final class GrantsForCreateTableMigrationSniff implements Sniff
Yes, can also use something like
```
$ecsConfig->skip([
        GrantsForCreateTableMigrationSniff::class => [
            'migrations/Version2021*',
            'migrations/Version2022*',
        ],
    ]);
```

2023-11-08 05:42 UTC, alexndlm approved these changes

2023-11-08 05:42 UTC, alexndlm commented on tests/Sniffs/Migrations/GrantsForCreateTableMigrationSniff/Fixture/Wrong/MigrationWithCreateTableWithoutGrant.php
> +    public function migrate(): void
thanks

2023-11-08 09:58 UTC, egor-dev approved these changes

2023-11-08 10:01 UTC, merged