feature/Update-AddSeeAnnotationRector-to-support-attributes
eonx-com/easy-quality pull request #84
Opened 2023-11-02 18:17 UTC by BOB41K1987

- Update AddSeeAnnotationRector to support attributes

2023-11-03 05:20 UTC, alexndlm requested changes
Please fix CI

2023-11-07 09:09 UTC, roman-eonx approved these changes

2023-11-08 05:00 UTC, BOB41K1987 commented
> Please fix CI

Done

2023-11-08 05:38 UTC, alexndlm approved these changes

2023-11-08 09:55 UTC, merged