Update all packages
eonx-com/easy-quality pull request #87
Opened 2024-06-06 10:35 UTC by alexndlm

2024-06-06 15:27 UTC, ERuban requested changes

2024-06-06 15:27 UTC, ERuban commented on .github/workflows/php-ci.yml
> +                run: ${{ matrix.actions.run }}
Please, add the empty line at the end

2024-06-06 15:27 UTC, ERuban commented on config/ecs/eonx-set.php
> +        'max_line_breaks' => 2,
Not sure that it is a correct values, it looks that it should be `1`

2024-06-06 15:27 UTC, ERuban commented on config/ecs/eonx-set.php
What do you think about to start using new configuration approach?
https://github.com/easy-coding-standard/easy-coding-standard?tab=readme-ov-file#configure

2024-06-06 15:27 UTC, ERuban commented on config/ecs/eonx-set.php
The same for Rector

2024-06-06 15:28 UTC, ERuban commented
@alexndlm Also, have you tried to execute this one updated on some of the projects?

2024-06-07 14:29 UTC, alexndlm commented on .github/workflows/php-ci.yml
> +                uses: actions/checkout@v3
Thanks. Done.

2024-06-07 15:00 UTC, ERuban commented on .github/workflows/php-ci.yml
> +                uses: actions/checkout@v3
didn't see the changes)

2024-06-07 15:00 UTC, ERuban commented on .github/workflows/php-ci.yml
> +                uses: actions/checkout@v3
I'm about the versions of actions)

2024-06-07 21:09 UTC, alexndlm commented on .github/workflows/php-ci.yml
> +                uses: actions/checkout@v3
I have tried to respond to comment in Storm - I still didn't understand how to do it properly.

Now done.

2024-06-07 21:09 UTC, alexndlm commented on .github/workflows/php-ci.yml
> +                run: ${{ matrix.actions.run }}
Done

2024-06-07 21:11 UTC, alexndlm commented on config/ecs/eonx-set.php
> +        'max_line_breaks' => 2,
I have tested - it correct.

2024-06-07 21:12 UTC, alexndlm commented on config/ecs/eonx-set.php
Cool. Done.

2024-06-07 21:12 UTC, alexndlm commented
> @alexndlm Also, have you tried to execute this one updated on some of the projects?

Tested see https://github.com/eonx-com/payment-gateway-api-v3/pull/3298

and https://eonx.slack.com/archives/CH42SHSF9/p1717794220416679

2024-06-15 14:05 UTC, ERuban approved these changes

2024-06-15 16:29 UTC, BOB41K1987 requested changes

2024-06-15 16:29 UTC, BOB41K1987 commented on config/rector/eonx-set.php
> +        ExplicitBoolCompareRector::class,
What is the difference between `EonxExplicitBoolCompareRector` and `ExplicitBoolCompareRector`?

2024-06-15 16:29 UTC, BOB41K1987 commented on quality/ecs.php
>              '/testCountWithDifferentHashSucceeds/',
Do we really need this in the package?

2024-06-15 16:29 UTC, BOB41K1987 commented on quality/phpstan.neon
> +    			identifier: missingType.iterableValue
Don't we need to add `identifier: missingType.generics` as well? It is the replacement for a deprecated config option `checkGenericClassInNonGenericObjectType` that we use now

2024-06-15 16:29 UTC, BOB41K1987 commented on src/PhpMetricsChecker/Report/SearchReporter.php
> +        // @phpstan-ignore-next-line
Can we ignore a specific rule instead? Like `// @phpstan-ignore variable.undefined` or something

2024-06-15 16:29 UTC, BOB41K1987 commented on tests/Sniffs/AbstractSniffTestCase.php
> +            [$inputContents, $expectedContents] = Strings::split($fileContents, "#-----\r?\n#");
Let's keep the `SPLIT_LINE_REGEX` constant but with the new value.

2024-06-17 02:30 UTC, BOB41K1987 commented on src/PhpMetricsChecker/Report/SearchReporter.php
> +        // @phpstan-ignore-next-line
That was just an example:) I mean, ignore only a specific rule(rules) instead of ignoring all the rules for the next line.

2024-06-17 04:23 UTC, BOB41K1987 commented
Please, take a look at some errors we get in the Transact projects. Does that look fine for you or is it some sort of misconfig that needs to be fixed on either package or project level?
```
1) src/Infrastructure/EasySchedule/ApplicationScheduleProvider.php

    ---------- begin diff ----------
@@ -27,7 +27,8 @@
 final class ApplicationScheduleProvider implements ScheduleProviderInterface
 {
     public function __construct(
-        #[Autowire(env: 'APP_INVOICE_CREATION_SCHEDULE')] private string $createInvoicesCronExpression,
+        #[Autowire(env: 'APP_INVOICE_CREATION_SCHEDULE')]
+        private string $createInvoicesCronExpression,
     ) {
     }
    ----------- end diff -----------


Applied checkers:

 * PhpCsFixer\Fixer\FunctionNotation\MethodArgumentSpaceFixer
```

2024-06-17 04:23 UTC, BOB41K1987 commented
```
6) tests/Factory/Dispute/DisputeFactory.php

    ---------- begin diff ----------
@@ -21,7 +21,7 @@
 final class DisputeFactory extends AbstractFactory
 {
     /**
-     * {@inheritdoc}
+     * {@inheritDoc}
      */
     protected array $relationsToSync = [
         'transaction' => ['customer', 'merchant', 'currency'],
    ----------- end diff -----------


Applied checkers:

 * PhpCsFixer\Fixer\Phpdoc\PhpdocTagCasingFixer
```

2024-06-17 07:14 UTC, alexndlm commented
> Please, take a look at some errors we get in the Transact projects. Does that look fine for you or is it some sort of misconfig that needs to be fixed on either package or project level?
> 
> ```
> 1) src/Infrastructure/EasySchedule/ApplicationScheduleProvider.php
> 
>     ---------- begin diff ----------
> @@ -27,7 +27,8 @@
>  final class ApplicationScheduleProvider implements ScheduleProviderInterface
>  {
>      public function __construct(
> -        #[Autowire(env: 'APP_INVOICE_CREATION_SCHEDULE')] private string $createInvoicesCronExpression,
> +        #[Autowire(env: 'APP_INVOICE_CREATION_SCHEDULE')]
> +        private string $createInvoicesCronExpression,
>      ) {
>      }
>     ----------- end diff -----------
> 
> 
> Applied checkers:
> 
>  * PhpCsFixer\Fixer\FunctionNotation\MethodArgumentSpaceFixer
> ```

`MethodArgumentSpaceFixer` is configured somewhere inside ECS.

As for me, the fix looks good.

2024-06-17 07:16 UTC, alexndlm commented
> ```
> 6) tests/Factory/Dispute/DisputeFactory.php
> 
>     ---------- begin diff ----------
> @@ -21,7 +21,7 @@
>  final class DisputeFactory extends AbstractFactory
>  {
>      /**
> -     * {@inheritdoc}
> +     * {@inheritDoc}
>       */
>      protected array $relationsToSync = [
>          'transaction' => ['customer', 'merchant', 'currency'],
>     ----------- end diff -----------
> 
> 
> Applied checkers:
> 
>  * PhpCsFixer\Fixer\Phpdoc\PhpdocTagCasingFixer
> ```

Yes, this is correct - should be `inheritDoc`

2024-06-17 07:16 UTC, alexndlm commented on src/PhpMetricsChecker/Report/SearchReporter.php
> +        // @phpstan-ignore-next-line
Ignoring in config is a good option - where the error is gone, we will know about this.

2024-06-17 08:26 UTC, roman-eonx commented on quality/ecs.php
>              '/testCountWithDifferentHashSucceeds/',
Well, we can eliminate such exclusions and add them on the project level. But it's not about this PR.

2024-06-17 10:08 UTC, BOB41K1987 approved these changes

2024-06-17 10:20 UTC, roman-eonx approved these changes

2024-06-17 10:20 UTC, merged