Sorted api resource operations
eonx-com/easy-quality pull request #96
Opened 2024-12-12 08:51 UTC by alexandrtspl

* add ApiResource "operations" sorting support

2024-12-13 07:32 UTC, itorgov approved these changes
__eonx_placeholder__

2024-12-13 07:52 UTC, alexndlm requested changes

2024-12-13 07:52 UTC, alexndlm commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
>  final class SortedApiResourceOperationKeysSniff implements Sniff
I think we should deprecate this sniff and create a new one with `SortApiResourceOperationsSniff`, which will work only with `operations`.

@roman-eonx wdyt?

2024-12-13 07:53 UTC, alexndlm commented
Please check it on PG.

2024-12-13 07:53 UTC, alexandrtspl commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
>  final class SortedApiResourceOperationKeysSniff implements Sniff
Why? 90% of code is reused in this sniff.

2024-12-13 07:54 UTC, alexandrtspl commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
>  final class SortedApiResourceOperationKeysSniff implements Sniff
But I agree for us it's not useful anymore

2024-12-13 08:42 UTC, alexandrtspl commented
> Please check it on PG.

It's checked before PR

2024-12-13 09:04 UTC, alexandrtspl commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
>  final class SortedApiResourceOperationKeysSniff implements Sniff
Done

2024-12-13 14:41 UTC, alexndlm requested changes

2024-12-13 14:41 UTC, alexndlm commented on src/Sniffs/Attributes/SortedApiResourceOperationKeysSniff.php
>  final class SortedApiResourceOperationKeysSniff implements Sniff
Thanks

2024-12-16 03:11 UTC, alexandrtspl commented on src/Sniffs/Attributes/SortedApiResourceOperationsSniff.php
> +    private const API_RESOURCE_OPERATIONS_TO_PROCESS = ['operations'];
Done

2024-12-16 03:13 UTC, alexandrtspl commented on src/Sniffs/Attributes/SortedApiResourceOperationsSniff.php
> +    private function isNotAssociativeOperationsArrayOnly(array $items): bool
Yes. Array-style operations should be skipped anyway.

2024-12-16 03:16 UTC, alexandrtspl commented on src/Sniffs/Attributes/SortedApiResourceOperationsSniff.php
> +    private function isNotAssociativeOperationsArrayOnly(array $items): bool
Removed

2024-12-16 06:23 UTC, alexndlm approved these changes

2024-12-16 06:24 UTC, alexndlm commented on src/Sniffs/Attributes/SortedApiResourceOperationsSniff.php
> +    private const API_RESOURCE_OPERATIONS_TO_PROCESS = ['operations'];
thanks

2024-12-16 06:24 UTC, alexndlm commented on src/Sniffs/Attributes/SortedApiResourceOperationsSniff.php
> +    private function isNotAssociativeOperationsArrayOnly(array $items): bool
thanks

2024-12-16 08:34 UTC, merged